# Namespace is managed here (instead of via helm's create_namespace) so that
# it's guaranteed to exist before the masterkey Secret below is created.
resource "kubernetes_namespace_v1" "this" {
  count = var.create_namespace ? 1 : 0

  metadata {
    name = var.namespace
  }
}

# Zitadel's masterkey can't be passed as a plain Helm value -- the chart
# expects an existing Kubernetes Secret name (zitadel.masterkeySecretName)
# that it mounts as a volume, so bridge the Terraform-managed value
# (generated by _modules/zitadel-secrets) into one here.
resource "kubernetes_secret_v1" "masterkey" {
  metadata {
    name      = var.masterkey_secret_name
    namespace = var.namespace
  }

  data = {
    masterkey = var.masterkey
  }

  type = "Opaque"

  depends_on = [kubernetes_namespace_v1.this]
}

# Sensitive config -> rendered into the zitadel-secrets-yaml Secret,
# mounted alongside the zitadel-config-yaml ConfigMap. Built here (rather
# than interpolated into a YAML heredoc in the calling terragrunt.hcl) so
# plaintext secret values never appear in that module's rendered `values`
# strings.
locals {
  secret_values = yamlencode({
    zitadel = {
      secretConfig = {
        FirstInstance = {
          Org = {
            Human = {
              Password = var.admin_password
            }
          }
        }
        Database = {
          postgres = {
            User = {
              Password = var.db_app_password
            }
            Admin = {
              Password = var.db_admin_password
            }
          }
        }
        Caches = {
          Connectors = {
            Redis = {
              Password = var.redis_password
            }
          }
        }
      }
    }
  })
}

resource "helm_release" "this" {
  name             = var.release_name
  repository       = var.repository
  chart            = var.chart
  version          = var.chart_version
  namespace        = var.namespace
  create_namespace = false
  timeout          = var.timeout
  wait             = var.wait
  atomic           = var.atomic

  values = concat(var.values, [local.secret_values])

  depends_on = [
    kubernetes_namespace_v1.this,
    kubernetes_secret_v1.masterkey,
  ]
}

# The load balancer backing a Kubernetes Ingress (e.g. an ALB provisioned by
# the AWS Load Balancer Controller) isn't necessarily ready the instant helm
# reports the release as installed -- give it time to actually provision
# before reading its hostname back.
resource "time_sleep" "wait_for_ingress" {
  count = var.expose_ingress_hostname ? 1 : 0

  depends_on      = [helm_release.this]
  create_duration = "120s"
}

data "kubernetes_ingress_v1" "this" {
  count = var.expose_ingress_hostname ? 1 : 0

  metadata {
    name      = var.ingress_name
    namespace = var.namespace
  }

  depends_on = [time_sleep.wait_for_ingress]
}
