# -----------------------------------------------------------------------------
# ZITADEL applications migrated from the Lodge104 Auth0 tenant, declared via
# the ZITADEL Terraform provider
# (https://registry.terraform.io/providers/zitadel/zitadel/latest). The
# provider itself is generated by each env's zitadel-resources/terragrunt.hcl
# unit (not declared here) -- providers must not live in reusable child
# modules -- and authenticates using the FirstInstance.Org.Machine bootstrap
# admin's PAT, read back by the zitadel-release module.
#
# A dedicated organization + project groups every migrated application so
# they're clearly distinguishable from anything created directly through the
# ZITADEL console. See _common/zitadel-apps.hcl for the populated catalog.
# -----------------------------------------------------------------------------

resource "zitadel_org" "migration" {
  name       = var.org_name
  is_default = var.is_default_org
}

resource "zitadel_project" "migration" {
  org_id = zitadel_org.migration.id
  name   = var.project_name

  # Matches Auth0's default behavior: no ZITADEL-specific project role
  # checks/assertions are required for these migrated applications to keep
  # working the way they did in Auth0.
  project_role_assertion = false
  project_role_check     = false
  has_project_check      = false
}

resource "zitadel_application_oidc" "web" {
  for_each = var.oidc_web_apps

  org_id     = zitadel_org.migration.id
  project_id = zitadel_project.migration.id

  name                      = each.value.name
  redirect_uris             = each.value.redirect_uris
  post_logout_redirect_uris = each.value.post_logout_redirect_uris
  response_types            = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types = [
    "OIDC_GRANT_TYPE_AUTHORIZATION_CODE",
    "OIDC_GRANT_TYPE_REFRESH_TOKEN",
  ]
  app_type         = "OIDC_APP_TYPE_WEB"
  auth_method_type = "OIDC_AUTH_METHOD_TYPE_BASIC"
  dev_mode         = false
}

resource "zitadel_application_oidc" "public" {
  for_each = var.oidc_public_apps

  org_id     = zitadel_org.migration.id
  project_id = zitadel_project.migration.id

  name                      = each.value.name
  redirect_uris             = each.value.redirect_uris
  post_logout_redirect_uris = each.value.post_logout_redirect_uris
  response_types            = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types = [
    "OIDC_GRANT_TYPE_AUTHORIZATION_CODE",
    "OIDC_GRANT_TYPE_REFRESH_TOKEN",
  ]
  app_type         = each.value.app_type
  auth_method_type = "OIDC_AUTH_METHOD_TYPE_NONE"
  dev_mode         = false
}

resource "zitadel_application_api" "m2m" {
  for_each = var.api_apps

  org_id     = zitadel_org.migration.id
  project_id = zitadel_project.migration.id

  name             = each.value.name
  auth_method_type = each.value.auth_method_type
}
