# Namespace is managed here (instead of via helm's create_namespace) so that
# it's guaranteed to exist before the auth Secret below is created, and so
# sibling releases in the same namespace (e.g. the zitadel-release module)
# can safely set create_namespace = false and just depend on this module.
resource "kubernetes_namespace_v1" "this" {
  count = var.create_namespace ? 1 : 0

  metadata {
    name = var.namespace
  }
}

# Bridges the Terraform-managed AUTH password (generated by
# _modules/zitadel-secrets) into a Kubernetes Secret the chart's
# auth.existingSecret value can reference, instead of letting the chart
# generate/store its own -- keeps the value stable across reinstalls and
# consistent with what the zitadel-release module is configured to send as
# Caches.Connectors.Redis.Password.
resource "kubernetes_secret_v1" "auth" {
  metadata {
    name      = var.auth_secret_name
    namespace = var.namespace
  }

  data = {
    (var.auth_secret_key) = var.auth_password
  }

  type = "Opaque"

  depends_on = [kubernetes_namespace_v1.this]
}

resource "helm_release" "this" {
  name             = var.release_name
  repository       = var.repository
  chart            = var.chart
  version          = var.chart_version
  namespace        = var.namespace
  create_namespace = false
  timeout          = var.timeout
  wait             = var.wait
  atomic           = var.atomic

  values = concat(
    [
      yamlencode({
        auth = {
          existingSecret            = kubernetes_secret_v1.auth.metadata[0].name
          existingSecretPasswordKey = var.auth_secret_key
        }
      })
    ],
    var.values
  )

  depends_on = [
    kubernetes_namespace_v1.this,
    kubernetes_secret_v1.auth,
  ]
}
