# -----------------------------------------------------------------------------
# Zitadel-specific secrets that must exist *before* the zitadel Helm release
# is installed (masterkey, cache auth token) or before the in-cluster Valkey
# release is installed (auth token). Kept in a dedicated module -- same
# single-purpose convention as wp.lodge104.net's ses-smtp-user module --
# rather than folded into the Helm-release module, since the valkey-release
# module also depends on the auth token generated here.
# -----------------------------------------------------------------------------

# Zitadel's encryption masterkey must be exactly 32 bytes. It is used to
# encrypt/decrypt sensitive data (e.g. OTP secrets, private keys) at rest in
# the database, so it must remain stable across the lifetime of the
# instance -- Terraform-managed (not chart-autogenerated) so it survives
# upgrades/reinstalls.
resource "random_password" "masterkey" {
  length  = 32
  special = false
}

# Password for the Zitadel application database role. Zitadel's setup job
# creates this role itself (using the Aurora admin credentials), so no
# corresponding RDS resource needs to be created ahead of time.
resource "random_password" "db_app_password" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>?"
}

# In-cluster Valkey AUTH token. Generated here (rather than by the
# valkey-release module) because both the valkey and zitadel-release
# terragrunt units need the same value.
resource "random_password" "valkey_auth_token" {
  length  = 32
  special = false
}

# Aurora master (admin) password. Generated here (rather than by the rds
# module's manage_master_user_password = true) because the rds, and
# zitadel-release terragrunt units all need the same value, and reading it
# back from the AWS-managed Secrets Manager secret immediately after a fresh
# cluster is created is prone to a data-source race condition.
resource "random_password" "aurora_master_password" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>?"
}

resource "aws_secretsmanager_secret" "masterkey" {
  name                    = "${var.name_prefix}/zitadel-masterkey"
  description             = "Zitadel encryption masterkey."
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "masterkey" {
  secret_id     = aws_secretsmanager_secret.masterkey.id
  secret_string = random_password.masterkey.result
}

resource "aws_secretsmanager_secret" "db_app_password" {
  name                    = "${var.name_prefix}/zitadel-db-app-password"
  description             = "Password for the '${var.db_app_username}' Zitadel application database role."
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "db_app_password" {
  secret_id = aws_secretsmanager_secret.db_app_password.id
  secret_string = jsonencode({
    username = var.db_app_username
    password = random_password.db_app_password.result
  })
}

resource "aws_secretsmanager_secret" "valkey_auth_token" {
  name                    = "${var.name_prefix}/valkey-auth-token"
  description             = "In-cluster Valkey AUTH token for Zitadel caching."
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "valkey_auth_token" {
  secret_id     = aws_secretsmanager_secret.valkey_auth_token.id
  secret_string = random_password.valkey_auth_token.result
}

resource "aws_secretsmanager_secret" "aurora_master_password" {
  name                    = "${var.name_prefix}/aurora-master-password"
  description             = "Aurora PostgreSQL master (admin) password for ${var.name_prefix}."
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "aurora_master_password" {
  secret_id     = aws_secretsmanager_secret.aurora_master_password.id
  secret_string = random_password.aurora_master_password.result
}

# Initial FirstInstance bootstrap admin password. Generated here (instead of
# hardcoded in env.hcl) so no plaintext credential ever needs to be
# committed -- retrieve the generated value from Secrets Manager after
# apply, same as wp.lodge104.net's create_wordpress_admin_credentials
# pattern. PasswordChangeRequired = true (set in the zitadel-release
# values) forces a change on first login regardless.
resource "random_password" "admin_password" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>?"
}

resource "aws_secretsmanager_secret" "admin_credentials" {
  name                    = "${var.name_prefix}/zitadel-admin-credentials"
  description             = "Initial Zitadel FirstInstance bootstrap admin credentials."
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "admin_credentials" {
  secret_id = aws_secretsmanager_secret.admin_credentials.id
  secret_string = jsonencode({
    username = var.admin_username
    password = random_password.admin_password.result
  })
}
